### ISSUE TITLE
Tests failing after updating phpseclib 2.0.8

### ISSUE THREAD

**Issue by it-can** [fuel/core#2078]
Getting this error after updating phpseclib to 2.0.8

```
There were 3 errors:

1) Fuel\Core\Test_Crypt::test_encode_decode
ArgumentCountError: Too few arguments to function phpseclib\Crypt\Rijndael::__construct(), 0 passed in /fuel/core/classes/crypt.php on line 213 and exactly 1 expected

/app/vendor/phpseclib/phpseclib/phpseclib/Crypt/Rijndael.php:170
/fuel/core/classes/crypt.php:213
/fuel/core/classes/crypt.php:90
/fuel/core/classes/crypt.php:106
/fuel/core/classes/crypt.php:122
/fuel/core/tests/crypt.php:48

2) Fuel\Core\Test_Crypt::test_encode_decode_with_key
ArgumentCountError: Too few arguments to function phpseclib\Crypt\Rijndael::__construct(), 0 passed in /fuel/core/classes/crypt.php on line 213 and exactly 1 expected

/app/vendor/phpseclib/phpseclib/phpseclib/Crypt/Rijndael.php:170
/fuel/core/classes/crypt.php:213
/fuel/core/classes/crypt.php:90
/fuel/core/classes/crypt.php:106
/fuel/core/classes/crypt.php:122
/fuel/core/tests/crypt.php:59

3) Fuel\Core\Test_Crypt::test_encode_decode_large_data
ArgumentCountError: Too few arguments to function phpseclib\Crypt\Rijndael::__construct(), 0 passed in /fuel/core/classes/crypt.php on line 213 and exactly 1 expected

/app/vendor/phpseclib/phpseclib/phpseclib/Crypt/Rijndael.php:170
/fuel/core/classes/crypt.php:213
/fuel/core/classes/crypt.php:90
/fuel/core/classes/crypt.php:106
/fuel/core/classes/crypt.php:122
/fuel/core/tests/crypt.php:73
```
